### ISSUE TITLE
Bindings as JsonNode ignore top-level attributes

### ISSUE THREAD

**Issue by dschulten** [IBM/JSONata4Java#135]
When bindings contain variable assignments using attributes at the top-level, then the binding variables are ignored.

```
String json = "{ \"greeting"\: \"hello\" }";
ObjectNode rootContextNode = JACKSON.readTree(json);

String jsonata = "{ \"foo\": $bar, "say": greeting }"
Expression jsonataExpr = Expression.jsonata(jsonata);

ObjectNode bindingNode = JACKSON.createObjectNode();
bindingNode.put("bar", "baz"); // variables at top-level

JsonNode transformed = jsonataExpr.evaluate(rootContextNode, bindingNode);
```
transformed is:
```
{"say":"hello"}
```
expected:
```
{
  "foo": 42,
  "say": "hello"
}

If I wrap the binding values one level deep, e.g. into an object named "bindings", then $bindings.bar will work.
```

**Comment by wnm3** [comment]
Interesting problem. ANTLR was dealing with numbers just fine, but the string was interpreted as an IdContext rather than a StringContext so when it tried to look up baz in { "greeting","hello"} it was getting a value of null (not found) and so no assignment was made for the variable $baz. I've added a case to the Binding constructor to ensure a StringContext is used when the parser defaults its guess to an IdContext).

I tested with this:
````
public class Test {

	public static void main(String[] args) {

		ObjectMapper mapper = new ObjectMapper();
		String json = "{ \"greeting\": \"hello\" }";
		try {
			ObjectNode rootContextNode;
			rootContextNode = (ObjectNode) mapper.readTree(json);
			System.out
					.println("rootContextNode:\n" + mapper.writerWithDefaultPrettyPrinter().writeValueAsString(rootContextNode));
			String jsonata = "{ \"foo\": $bar, \"say\": greeting }";
			System.out.println("jsonata:\n" + mapper.writerWithDefaultPrettyPrinter().writeValueAsString(jsonata));
			Expression jsonataExpr = Expression.jsonata(jsonata);

			ObjectNode bindingNode = mapper.createObjectNode();
			bindingNode.put("bar", "baz"); // variables at top-level
			System.out.println("bindingNode:\n" + mapper.writerWithDefaultPrettyPrinter().writeValueAsString(bindingNode));

			JsonNode transformed = jsonataExpr.evaluate(rootContextNode, bindingNode);
			System.out.println("transformed:\n" + mapper.writerWithDefaultPrettyPrinter().writeValueAsString(transformed));
			
			Expression jsonatax= Expression.jsonata(jsonata);
			jsonatax.assign("bar", "baz");
			transformed = jsonatax.evaluate(rootContextNode);
			System.out.println("transformed:\n" + mapper.writerWithDefaultPrettyPrinter().writeValueAsString(transformed));

		} catch (JsonMappingException e2) {
			// TODO Auto-generated catch block
			e2.printStackTrace();
		} catch (JsonProcessingException e2) {
			// TODO Auto-generated catch block
			e2.printStackTrace();
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (EvaluateException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
````
Yielding this output:
````
rootContextNode:
{
  "greeting" : "hello"
}
jsonata:
"{ \"foo\": $bar, \"say\": greeting }"
bindingNode:
{
  "bar" : "baz"
}
transformed:
{
  "foo" : "baz",
  "say" : "hello"
}
transformed:
{
  "foo" : "baz",
  "say" : "hello"
}
````

The fix is in the Binding.java constructor with added test for IdContext:
````
         } else if (tree instanceof MappingExpressionParser.IdContext) {
         	_expr = (ExprContext)new MappingExpressionParser.StringContext(new ExprContext());
         	_expr.addChild((TerminalNode)tree.getChild(0));
         	_type = BindingType.VARIABLE;
         	_varname = varName;
         }
````

**Comment by wnm3** [comment]
Please close if you believe this issue is resolved. You'll have to build a copy of the jar file until I make a new release. If you loaded into Eclipse, you can right click on the pom.xml and select Build maven ... then use clean install as the goals.

**Comment by wnm3** [comment]
I pushed version 1.4.9 to Maven Central just now -- it should be available tomorrow for download.

**Comment by dschulten** [comment]
wow that was fast. Thank you!

**Comment by dschulten** [comment]
The issue as reported is fixed, but it has created followup issues which appear to be caused by the recognition of numeric and arithmetic expressions:

```
    @Test
    public void issue135IsFixed() throws Exception {
        String json = "{ \"greeting\": \"hello\" }";
        JsonNode rootContextNode = JACKSON.readTree(json);

        String jsonata = "{ \"foo\": $bar, \"say\": greeting, \"uuid\": $nonNumeric, \"numericString\": $numberAsString }";
        Expression jsonataExpr = Expression.jsonata(jsonata);

        ObjectNode bindingNode = JACKSON.createObjectNode();
        bindingNode //
            .put("bar", "baz")
            .put("numberAsString", "0815")
            .put("nonNumeric", "123e4567-e89b-12d3-a456-426614174000");

        JsonNode transformed = jsonataExpr.evaluate(rootContextNode, bindingNode);
        System.out.println(transformed);
    }

```
Expected:
```
{
  "foo": "baz",
  "say": "hello",
  "uuid": "123e4567-e89b-12d3-a456-426614174000",
  "numericString": "0815"
}
```

But fails with:

<details>
  <summary>Stacktrace</summary>

```
com.api.jsonata4java.expressions.EvaluateRuntimeException: Number out of range: "123e4567"

	at com.api.jsonata4java.expressions.utils.NumberUtils.convertNumberToValueNode(NumberUtils.java:74)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitNumber(ExpressionsVisitor.java:2064)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitNumber(ExpressionsVisitor.java:92)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$NumberContext.accept(MappingExpressionParser.java:405)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:801)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitAddsub_op(ExpressionsVisitor.java:825)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitAddsub_op(ExpressionsVisitor.java:92)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$Addsub_opContext.accept(MappingExpressionParser.java:363)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:801)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitAddsub_op(ExpressionsVisitor.java:825)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitAddsub_op(ExpressionsVisitor.java:92)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$Addsub_opContext.accept(MappingExpressionParser.java:363)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:801)
	at com.api.jsonata4java.Expression.evaluate(Expression.java:164)
	at com.api.jsonata4java.Expression.evaluate(Expression.java:196)
	at com.api.jsonata4java.Expression.evaluate(Expression.java:231)
	at de.iteos.kmc.middleware.sbw.unip.service.mapper.JsonataMapperTest.issue135IsFixed(JsonataMapperTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

</details>

Further observations:

- If I put an A in front of `"123e4567-e89b-..."` as in `"A123e4567-e89b-..."`, the exception no longer occurs, but no `numberAsString` attribute is included in the output.
- If I remove the minus signs and shorten to `"A123e4567"`, the uuid gets included.
- The output contains `"numericString": 0` rather than `"numericString": "0815"`

**Comment by wnm3** [comment]
Thanks for finding this bug. The issue was, Bindings were attempting to interpret the values being set as expressions so it was attempting to perform subtraction on the parts of the uuid and when it hit the e in 123e4567 it thought the exponent was 4567...

I've repaired this so Strings are taken as Strings, Numbers as numbers, etc.

Please close if you believe the problems are resolved.  I've checked in the fixes and linked them to this issue and I'll release version 1.5.5 today.
