### ISSUE TITLE
Using this framework in a distributed framework like Apache Beam or Spark

### ISSUE THREAD

**Issue by pradeepcheers** [IBM/JSONata4Java#149]
The `Expressions.parse("")` is a static method and hence can't be used in distributed frameworks such as Apache Beam / Apache Spark. Is there a way to make it non -static so that this method can be serialized. At the moment I'm getting the following error.

```
Caused by: java.io.NotSerializableException: com.api.jsonata4java.expressions.Expressions
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at org.apache.beam.sdk.util.SerializableUtils.serializeToByteArray(SerializableUtils.java:55)```

**Comment by pradeepcheers** [comment]
This is at the moment sorted by not using Expressions as instance variable but with this approach we need to parse the expression every time in each one of the worker.

**Comment by wnm3** [comment]
I am happy to make the Expressions class (and any others I find) Serializable so you can avoid the error above. I'll try to run through the classes to ensure they have this setting. However, I'm not sure what will happen with the classes generated by ANTLR... we'll soon find out ;^)
