### ISSUE TITLE
Passing a JsonNode which contains a key with null value leads to ParseException

### ISSUE THREAD

**Issue by JDUNNIN** [IBM/JSONata4Java#165]
Calling `Expression.evaluate` with input JsonNode that contains a field with a null value (see `Body` below) causes a `ParseException` with no meaningful error message.

When this method is creating the `List<Binding>` object it should take into account null values and skip these or throw a `ParseException` with a detailed message explaining that null value is not valid.

JsonNode content
```
 {"QueryParameters":{},"PathParameters":{"id":"000150"},"Body":null,"Cookies":{}}
```
Stacktrace:
```
com.api.jsonata4java.expressions.ParseException: line 1:0 at [@0,0:-1='<EOF>',<-1>,1:0]: mismatched input '<EOF>' expecting {'(', 'true', 'false', STRING, 'null', '[', '{', '$', '$$', '**', NUMBER, FUNCTIONID, '*', '-', VAR_ID, ID}
  at com.api.jsonata4java.expressions.Expressions.parse(Expressions.java:116)
  at com.api.jsonata4java.Binding.<init>(Binding.java:68)
  at com.api.jsonata4java.Expression.evaluate(Expression.java:228)
```

**Comment by wnm3** [comment]
I'm not sure what to do with this as I have added a dataobject_b.json with your content and run the Tester passing that filename and if I reference Body as the expression I do indeed get null returned.
```
Attempting to load JSON from file: dataobject_b.json
Using json:
{
  "QueryParameters" : { },
  "PathParameters" : {
    "id" : "000150"
  },
  "Body" : null,
  "Cookies" : { }
}
Enter jsonata expression (or q to quit):
Body
null
```
e.g., I don't get a ParseException referenced above.

The Expressions.parse takes a String as input so I can't imagine Body being anything but a null value (which internally we track as an instance of a NullNode (since we use an actual null to represent ** No Match ** output in the Tester).

**Comment by JDUNNIN** [comment]
I will try write a test for this in our code to see if I can spot a difference anywhere. We had observed null checking being a little buggy at `1.4.8` so could be related as `1.5.8` resolved the issues.
