### ISSUE TITLE
$spread raise com.api.jsonata4java.expressions.EvaluateRuntimeException: Argument 2 of function $spread does not match function signature

### ISSUE THREAD

**Issue by sedlacl** [IBM/JSONata4Java#175]
Try https://try.jsonata.org/hM58d88xp in jsonatajava.

`$spread(Account.Order.Product).*`
raise
`com.api.jsonata4java.expressions.EvaluateRuntimeException: Argument 2 of function $spread does not match function signature
	at com.api.jsonata4java.expressions.functions.SpreadFunction.invoke(SpreadFunction.java:92)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitFunction_call(ExpressionsVisitor.java:1785)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitFunction_call(ExpressionsVisitor.java:99)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$Function_callContext.accept(MappingExpressionParser.java:318)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:811)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitPath(ExpressionsVisitor.java:2403)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitPath(ExpressionsVisitor.java:99)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$PathContext.accept(MappingExpressionParser.java:476)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:811)
	at com.api.jsonata4java.Expression.evaluate(Expression.java:173)
	at usy.idsmari.test.abl.IdsmariTestAbl.jsonataTest(IdsmariTestAbl.java:95)
	at usy.idsmari.test.api.IdsmariTestController.jsonatatest(IdsmariTestController.java:31)
	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at ...`

**workaround**
Put $spread function into brackets:

`($spread(Account.Order.Product)).*`

**Comment by sedlacl** [comment]
Seems to be trouble with useContext.

Similiar problem:
https://try.jsonata.org/KyWb9eOTo

`
(
    $list:=Account.Order;
    $list{`OrderID`:$}
)`

returns empty result
`{
}`

but 
`(
    $list:=Account.Order;
    ($list){`OrderID`:$}
)` works fine

**Comment by wnm3** [comment]
Thank you -- I'll try to look into this today.

**Comment by sedlacl** [comment]
Seems to be two different issues.

- First one seems to be related to conditions in FunctionUtils.useContextVariable
``
 public static boolean useContextVariable(Function fct, Function_callContext ctx, String signature) {
    if (ctx == null) { // || ctx.getParent() == null) {
      return false;
    }

    int argCount = FunctionBase.getArgumentCount(ctx);
    if (argCount == 0) {
      // no arguments so try to get from context
      return true;
    }

    ParserRuleContext prc = ctx.getParent();
    if (prc != null && prc instanceof Fct_chainContext) {
      // you are called from a chain so use current context
      return true;
    }

    int optional = getOptionalArgCount(signature);

    int min = fct.getMinArgs();
    int max = fct.getMaxArgs();
    // check when no optional arguments presented
    if (min == max) {
      return argCount < min;
    }

    //all arguments are set //!!! this condition is missing
    if (argCount==max)
    {
      return false;
    }

    if (argCount < max-optional) {
      // should have required argument in context
      return true;
    }
    // does the signature permit use of the context as a argument
    if (signature.indexOf("-") >= 0 && prc != null && prc instanceof PathContext) {
      return true;
    }

    return false;
  }

`` 

- The second one https://try.jsonata.org/KyWb9eOTo is related to update in ExpressionsVisitor.visitObject according to issue

https://github.com/IBM/JSONata4Java/issues/136

**Comment by wnm3** [comment]
I've pushed some changes to address both problems. You can pull and use:
mvn clean install 
in the JSONata4Java directory to build a new jar file in the target directory. 

If you believe this has solved the problem, I'll cut a new release and push to Maven Central.

I'd had some other work in progress that was checked in -- it didn't solve the problem in the other issue #167 because ANTLR isn't serializable...

**Comment by sedlacl** [comment]
Thanks for great and fast work. I'm on vacation till monday, so I try it then and let you know.

**Comment by wnm3** [comment]
Has this issue been resolved to your satisfaction?
