### ISSUE TITLE
Function declaraction with parameter throws errors

### ISSUE THREAD

**Issue by Maevy** [IBM/JSONata4Java#21]
Hi,
I was trying to use JSONata4Java, however i realized that the framework cannot map the parameter from a function, here is an example.

```
$abc := function($x){
  $x*$x
}; $abc(5)
```
The result is

```
com.api.jsonata4java.expressions.EvaluateException: $abc is unknown (e.g., unassigned variable)

	at com.api.jsonata4java.expressions.Expressions.evaluate(Expressions.java:142)
	at com.api.jsonata4java.text.expressions.utils.Utils.test(Utils.java:162)
	at com.api.jsonata4java.test.expressions.JsonataUnitTests.runTest(JsonataUnitTests.java:1222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.api.jsonata4java.expressions.EvaluateRuntimeException: $abc is unknown (e.g., unassigned variable)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitVar_recall(ExpressionsVisitor.java:1975)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitVar_recall(ExpressionsVisitor.java:81)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$Var_recallContext.accept(MappingExpressionParser.java:645)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitComp_op(ExpressionsVisitor.java:777)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitComp_op(ExpressionsVisitor.java:81)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$Comp_opContext.accept(MappingExpressionParser.java:797)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.Expressions.evaluate(Expressions.java:140)
	... 32 more
```

Then I cloned the project and looked up the JsonataUnitTests.java and realized that the testcase also fails.

`{ "null", "($factorial:= function($x){$x <= 1 ? 1 : $x * $factorial($x-1)}; $factorial(4))", "24" }`

Can u help ?

I realized that maven is not executing most of the tests due to naming Conventions, i recommend writing the tests with a naming convention ThisMyTest.java without the plural.

Kind regards

**Comment by wnm3** [comment]
Thank you for your input. I'll look into it tonight and hope to have a fix for you soon. I agree with your comments about the test cases as well and will update the issue for cleaning them up to incorporate your feedback. I'll provide you status tomorrow one way or the other.

**Comment by ashauer** [comment]
Hi Nathaniel,

I'm a colleague of @Maevy. To be a bit more precise, this expression should work to really make our use case work (pay attention to the inner brackets within the function!):

`(
  $abc := function($x) {(
    $y := 2 * $x;

    $x + $y
  )};

  $abc(5)
)`

Thx-a-lot for your quick response and your support!

**Comment by wnm3** [comment]
I was able to add the Function_callContext processing to ensure assignment of expression values to the function's parameters.

Added these calls in BasicExpressionTest.java:
```
      // issue #21
      simpleTest("( $abc := function($x) {( $y := 2 * $x; $x + $y )}; $abc(5))",15,jsonObj2);
      simpleTest("( $abc := function($x) {( $y := 2 * $x; $x + $y )}; $abc(Age))",84,jsonObj2);
```
which outputs 
```
* ( $abc := function($x) {( $y := 2 * $x; $x + $y )}; $abc(5)) returned 15
* ( $abc := function($x) {( $y := 2 * $x; $x + $y )}; $abc(Age)) returned 84
```

I've checked in version 1.1.1 which should be posted to the Maven central repository later today.

**Comment by ashauer** [comment]
👍 Works now!

@Maevy, issue can be closed! I tested it...

**Comment by wnm3** [comment]
Thanks again for the nicely documented bug with complete test case!

**Comment by ashauer** [comment]
You're welcome...
