### ISSUE TITLE
NoClassDefFoundError: com.api.jsonata4java.expressions.JS4JDate

### ISSUE THREAD

**Issue by JDUNNIN** [IBM/JSONata4Java#301]
Hi, I hit this error when trying to use JSONata4Java with java:
```
java.version = 1.8.0_231
java.runtime = Java(TM) SE Runtime Environment (8.0.6.0 - pmz6480sr6-20190816_01(SR6))
```

This is the stack trace. 
```
[3/8/24 12:00:10:565 GMT] 00000045 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.api.jsonata4java.expressions.FrameEnvironment.<init>:78'
java.lang.NoClassDefFoundError: com.api.jsonata4java.expressions.JS4JDate
	at com.api.jsonata4java.expressions.FrameEnvironment.<init>(FrameEnvironment.java:78)
	at com.api.jsonata4java.expressions.Expressions.<init>(Expressions.java:132)
	at com.api.jsonata4java.expressions.Expressions.parse(Expressions.java:122)
```

Is this a known issue at all? I couldn't see anything for it in issues. I had run the same scenario quite a long time ago successfully and we've updated our JSONata4Java level since then - just a guess whether it is something to do with Java 11 changes that went in. Currently using `2.4.3`. 

I can see the class inside the jar file installed.
![image](https://github.com/IBM/JSONata4Java/assets/25950902/d29c3ce0-d812-41d3-b678-177d8f5f8413)

**Comment by JDUNNIN** [comment]
This seemed to go away when I restarted my server - unknown why.
