### ISSUE TITLE
spread function throwing java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by vish35** [IBM/JSONata4Java#313]
I am trying to create combination list using 2 array with spread function but its giving error "Exception in thread "main" java.lang.OutOfMemoryError: Java heap space". For example first array contains 4 values and second array contains 2 values, with spread and map function it should generate array having 8 combinations where it is generating 255 combinations and it has multiple duplicate combinations. With large no of combinations, spread function throwing "Exception in thread "main" java.lang.OutOfMemoryError". This is working in JSONata exerciser but not with jsonata4java library. I checked in 1.7.9, 2.1.2 and 2.5.0 version where I faced same issue. I think issue can be with jsonata4java package and not in jsonata-js which I believe jsonata exerciser using same. This is link for jsonata exerciser -https://try.jsonata.org/0iUm2E-py

 Error logs for outOfMemory error:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3512)
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
	at java.base/java.util.ArrayList.add(ArrayList.java:454)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at com.fasterxml.jackson.databind.node.ArrayNode._add(ArrayNode.java:1202)
	at com.fasterxml.jackson.databind.node.ArrayNode.add(ArrayNode.java:433)
	at com.api.jsonata4java.expressions.functions.SpreadFunction.concat(SpreadFunction.java:201)
	at com.api.jsonata4java.expressions.functions.SpreadFunction.append(SpreadFunction.java:191)
	at com.api.jsonata4java.expressions.functions.SpreadFunction.spread(SpreadFunction.java:154)
	at com.api.jsonata4java.expressions.functions.SpreadFunction.invoke(SpreadFunction.java:87)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitFunction_call(ExpressionsVisitor.java:1823)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitFunction_call(ExpressionsVisitor.java:96)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$Function_callContext.accept(MappingExpressionParser.java:351)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:809)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitVar_assign(ExpressionsVisitor.java:2956)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitVar_assign(ExpressionsVisitor.java:96)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$Var_assignContext.accept(MappingExpressionParser.java:382)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:809)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitParens(ExpressionsVisitor.java:2438)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitParens(ExpressionsVisitor.java:96)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$ParensContext.accept(MappingExpressionParser.java:191)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visit(ExpressionsVisitor.java:809)
	at com.api.jsonata4java.Expression.evaluate(Expression.java:225)
	at org.example.Main.main(Main.java:84)
```

Please let me know if I am doing anything wrong or its known issue

**Comment by wnm3** [comment]
Thank you @vish35 I've pushed a release 2.5.1 to Maven Central (should be there in a few hours) that incorporates your fix. If you are happy with this please close this issue.

**Comment by vish35** [comment]
thank you @wnm3. Can we get ETA, when 2.5.1 version will be available in Maven Central?

**Comment by wnm3** [comment]
Sorry, it should have gone on 7/25. I've pushed it again. Hopefully in an hour or two.

**Comment by vish35** [comment]
Thank you, I see its released now. Closing this issue
